FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY scripts/ ./scripts/

# Esperar a que Kafka esté listo y luego crear topics
CMD ["sh", "-c", "sleep 15 && node scripts/create-topics.js"]